import re
TAG_SIGNALS_GEN = [
    ('age: - 18', re.compile(r'\b\-\ 18\b', re.I)),
    ('age:18-24', re.compile(r'\b18\-24\b', re.I)),
    ('age:25-34', re.compile(r'\b25\-34\b', re.I)),
    ('age:35-44', re.compile(r'\b35\-44\b', re.I)),
    ('age:45-54', re.compile(r'\b45\-54\b', re.I)),
    ('age:55-64', re.compile(r'\b55\-64\b', re.I)),
    ('age: + 65', re.compile(r'\b\+\ 65\b', re.I)),
    ('gender:male', re.compile(r'\bmale\b', re.I)),
    ('gender:female', re.compile(r'\bfemale\b', re.I)),
    ('gender:Other', re.compile(r'\bother\b', re.I)),
    ('education:highschool', re.compile(r'\bhighschool\b', re.I)),
    ('education:bachelor', re.compile(r'\bbachelor\b', re.I)),
    ('education:master', re.compile(r'\bmaster\b', re.I)),
    ('education:phd', re.compile(r'\bphd\b', re.I)),
    ('education:college', re.compile(r'\bcollege\b', re.I)),
    ('country:fr', re.compile(r'\bfr\b', re.I)),
    ('country:ma', re.compile(r'\bma\b', re.I)),
    ('country:es', re.compile(r'\bes\b', re.I)),
    ('country:us', re.compile(r'\bus\b', re.I)),
    ('city:casablanca', re.compile(r'\bcasablanca\b', re.I)),
    ('city:rabat', re.compile(r'\brabat\b', re.I)),
    ('city:paris', re.compile(r'\bparis\b', re.I)),
    ('city: 100 Pays 200 Villes', re.compile(r'\b100\ pays\ 200\ villes\b', re.I)),
    ('language:fr', re.compile(r'\bfr\b', re.I)),
    ('language:ar', re.compile(r'\bar\b', re.I)),
    ('language:en', re.compile(r'\ben\b', re.I)),
    ('language:esp', re.compile(r'\besp\b', re.I)),
    ('personality:analytical', re.compile(r'\banalytical\b', re.I)),
    ('personality:creative', re.compile(r'\bcreative\b', re.I)),
    ('personality: Social', re.compile(r'\bsocial\b', re.I)),
    ('personality: Procedural', re.compile(r'\bprocedural\b', re.I)),
    ('preference:premium', re.compile(r'\bpremium\b', re.I)),
    ('preference:lowcost', re.compile(r'\blowcost\b', re.I)),
    ('preference: Innovative', re.compile(r'\binnovative\b', re.I)),
    ('preference: quality', re.compile(r'\bquality\b', re.I)),
    ('interest: IT&AI&Automation', re.compile(r'\bit\&ai\&automation\b', re.I)),
    ('interest: Technology&innovation', re.compile(r'\btechnology\&innovation\b', re.I)),
    ('interest:properties', re.compile(r'\bproperties\b', re.I)),
    ('interest: physics & biology', re.compile(r'\bphysics\ \&\ biology\b', re.I)),
    ('interest: Art&design', re.compile(r'\bart\&design\b', re.I)),
    ('interest: cars&plane', re.compile(r'\bcars\&plane\b', re.I)),
    ('motivation:performance', re.compile(r'\bperformance\b', re.I)),
    ('motivation:simplicity', re.compile(r'\bsimplicity\b', re.I)),
    ('attitude:early-adopter', re.compile(r'\bearly\-adopter\b', re.I)),
    ('attitude:late-adopter', re.compile(r'\blate\-adopter\b', re.I)),
    ('expectation:quality', re.compile(r'\bquality\b', re.I)),
    ('expectation:speed', re.compile(r'\bspeed\b', re.I)),
    ('style:premium', re.compile(r'\bpremium\b', re.I)),
    ('style:basic', re.compile(r'\bbasic\b', re.I)),
    ('role: guest', re.compile(r'\bguest\b', re.I)),
    ('role: authenticated', re.compile(r'\bauthenticated\b', re.I)),
    ('role: indentified', re.compile(r'\bindentified\b', re.I)),
    ('role : possibly identfied', re.compile(r'\bpossibly\ identfied\b', re.I)),
    ('access: role based', re.compile(r'\brole\ based\b', re.I)),
    ('access:guest based', re.compile(r'\bguest\ based\b', re.I)),
    ('company-size:1-10', re.compile(r'\b1\-10\b', re.I)),
    ('company-size:10-50', re.compile(r'\b10\-50\b', re.I)),
    ('company-size:50-200', re.compile(r'\b50\-200\b', re.I)),
    ('company-size:200-1000', re.compile(r'\b200\-1000\b', re.I)),
    ('company-size:1000+', re.compile(r'\b1000\+\b', re.I)),
    ('revenue:1m', re.compile(r'\b1m\b', re.I)),
    ('revenue:5m', re.compile(r'\b5m\b', re.I)),
    ('revenue:20m+', re.compile(r'\b20m\+\b', re.I)),
    ('market:local', re.compile(r'\blocal\b', re.I)),
    ('market:regional', re.compile(r'\bregional\b', re.I)),
    ('market:global', re.compile(r'\bglobal\b', re.I)),
    ('growth:fast', re.compile(r'\bfast\b', re.I)),
    ('growth:stable', re.compile(r'\bstable\b', re.I)),
    ('ownership:private', re.compile(r'\bprivate\b', re.I)),
    ('ownership:public', re.compile(r'\bpublic\b', re.I)),
    ('model:b2b', re.compile(r'\bb2b\b', re.I)),
    ('model: b2g', re.compile(r'\bb2g\b', re.I)),
    ('model:b2c', re.compile(r'\bb2c\b', re.I)),
    ('model:service', re.compile(r'\bservice\b', re.I)),
    ('model: integration', re.compile(r'\bintegration\b', re.I)),
    ('model: distribution', re.compile(r'\bdistribution\b', re.I)),
    ('industry:finance', re.compile(r'\bfinance\b', re.I)),
    ('industry:health', re.compile(r'\bhealth\b', re.I)),
    ('industry:retail', re.compile(r'\bretail\b', re.I)),
    ('industry:manufacturing', re.compile(r'\bmanufacturing\b', re.I)),
    ('industry:telco', re.compile(r'\btelco\b', re.I)),
    ('industry: Service', re.compile(r'\bservice\b', re.I)),
    ('industry:primary sectors', re.compile(r'\bprimary\ sectors\b', re.I)),
    ('industry:insurance', re.compile(r'\binsurance\b', re.I)),
    ('industry:education', re.compile(r'\beducation\b', re.I)),
    ('industry:transport', re.compile(r'\btransport\b', re.I)),
    ('industry:energy', re.compile(r'\benergy\b', re.I)),
    ('industry:agriculture', re.compile(r'\bagriculture\b', re.I)),
    ('regulation:gdpr', re.compile(r'\bgdpr\b', re.I)),
    ('regulation:hipaa', re.compile(r'\bhipaa\b', re.I)),
    ('sector:public', re.compile(r'\bpublic\b', re.I)),
    ('sector:private', re.compile(r'\bprivate\b', re.I)),
    ('role:cto', re.compile(r'\bcto\b', re.I)),
    ('role:ceo', re.compile(r'\bceo\b', re.I)),
    ('role:cfo', re.compile(r'\bcfo\b', re.I)),
    ('role:cmo', re.compile(r'\bcmo\b', re.I)),
    ('role:product-manager', re.compile(r'\bproduct\-manager\b', re.I)),
    ('role:developer', re.compile(r'\bdeveloper\b', re.I)),
    ('role:data-analyst', re.compile(r'\bdata\-analyst\b', re.I)),
    ('role:designer', re.compile(r'\bdesigner\b', re.I)),
    ('role:consultant', re.compile(r'\bconsultant\b', re.I)),
    ('role:engineer', re.compile(r'\bengineer\b', re.I)),
    ('role:administrator', re.compile(r'\badministrator\b', re.I)),
    ('seniority:executive', re.compile(r'\bexecutive\b', re.I)),
    ('seniority:director', re.compile(r'\bdirector\b', re.I)),
    ('seniority:manager', re.compile(r'\bmanager\b', re.I)),
    ('seniority:staff', re.compile(r'\bstaff\b', re.I)),
    ('department:it', re.compile(r'\bit\b', re.I)),
    ('department:finance', re.compile(r'\bfinance\b', re.I)),
    ('department:marketing', re.compile(r'\bmarketing\b', re.I)),
    ('buyer:buyer', re.compile(r'\bbuyer\b', re.I)),
    ('buyer:no', re.compile(r'\bno\b', re.I)),
    ('buyer: influencer', re.compile(r'\binfluencer\b', re.I)),
    ('buyer: recommender', re.compile(r'\brecommender\b', re.I)),
    ('buyer: initiator', re.compile(r'\binitiator\b', re.I)),
    ('buyer: decider', re.compile(r'\bdecider\b', re.I)),
    ('buyer role: End user', re.compile(r'\bend\ user\b', re.I)),
    ('budget:low', re.compile(r'\blow\b', re.I)),
    ('budget:medium', re.compile(r'\bmedium\b', re.I)),
    ('budget:high', re.compile(r'\bhigh\b', re.I)),
    ('budget:none', re.compile(r'\bnone\b', re.I)),
    ('authority:high', re.compile(r'\bhigh\b', re.I)),
    ('authority:medium', re.compile(r'\bmedium\b', re.I)),
    ('authority:low', re.compile(r'\blow\b', re.I)),
    ('authority:none', re.compile(r'\bnone\b', re.I)),
    ('need:urgent', re.compile(r'\burgent\b', re.I)),
    ('need:medium', re.compile(r'\bmedium\b', re.I)),
    ('need:low', re.compile(r'\blow\b', re.I)),
    ('need:none', re.compile(r'\bnone\b', re.I)),
    ('timing:now', re.compile(r'\bnow\b', re.I)),
    ('timing:3months', re.compile(r'\b3months\b', re.I)),
    ('timing:6months', re.compile(r'\b6months\b', re.I)),
    ('timing : none', re.compile(r'\bnone\b', re.I)),
    ('fit:strong', re.compile(r'\bstrong\b', re.I)),
    ('fit:weak', re.compile(r'\bweak\b', re.I)),
    ('fit:medium', re.compile(r'\bmedium\b', re.I)),
    ('fit: none', re.compile(r'\bnone\b', re.I)),
    ('sessions:daily', re.compile(r'\bdaily\b', re.I)),
    ('sessions:weekly', re.compile(r'\bweekly\b', re.I)),
    ('sessions:monthly', re.compile(r'\bmonthly\b', re.I)),
    ('usage:low', re.compile(r'\blow\b', re.I)),
    ('usage:medium', re.compile(r'\bmedium\b', re.I)),
    ('usage:high', re.compile(r'\bhigh\b', re.I)),
    ('active:7days', re.compile(r'\b7days\b', re.I)),
    ('active:30days', re.compile(r'\b30days\b', re.I)),
    ('events:10+', re.compile(r'\b10\+\b', re.I)),
    ('events:100+', re.compile(r'\b100\+\b', re.I)),
    ('engagement:power-user', re.compile(r'\bpower\-user\b', re.I)),
    ('engagement:occasional', re.compile(r'\boccasional\b', re.I)),
    ('login:frequent', re.compile(r'\bfrequent\b', re.I)),
    ('login:rare', re.compile(r'\brare\b', re.I)),
    ('consumption:high', re.compile(r'\bhigh\b', re.I)),
    ('consumption:low', re.compile(r'\blow\b', re.I)),
    ('stickiness:high', re.compile(r'\bhigh\b', re.I)),
    ('stickiness:low', re.compile(r'\blow\b', re.I)),
    ('depth:shallow', re.compile(r'\bshallow\b', re.I)),
    ('depth:deep', re.compile(r'\bdeep\b', re.I)),
    ('feature-depth:basic', re.compile(r'\bbasic\b', re.I)),
    ('feature-depth:medium', re.compile(r'\bmedium\b', re.I)),
    ('adoption:features 1', re.compile(r'\bfeatures\ 1\b', re.I)),
    ('adoption:features 2', re.compile(r'\bfeatures\ 2\b', re.I)),
    ('adoption:features 3', re.compile(r'\bfeatures\ 3\b', re.I)),
    ('adoption:features 4', re.compile(r'\bfeatures\ 4\b', re.I)),
    ('adoption:features 5', re.compile(r'\bfeatures\ 5\b', re.I)),
    ('adoption:features 6', re.compile(r'\bfeatures\ 6\b', re.I)),
    ('adoption:features 7', re.compile(r'\bfeatures\ 7\b', re.I)),
    ('email:opened', re.compile(r'\bopened\b', re.I)),
    ('email:clicked', re.compile(r'\bclicked\b', re.I)),
    ('email:ignored', re.compile(r'\bignored\b', re.I)),
    ('push:enabled', re.compile(r'\benabled\b', re.I)),
    ('push:disabled', re.compile(r'\bdisabled\b', re.I)),
    ('web:active', re.compile(r'\bactive\b', re.I)),
    ('web:inactive', re.compile(r'\binactive\b', re.I)),
    ('loyalty:high', re.compile(r'\bhigh\b', re.I)),
    ('loyalty:medium', re.compile(r'\bmedium\b', re.I)),
    ('loyalty:low', re.compile(r'\blow\b', re.I)),
    ('promotion:responsive', re.compile(r'\bresponsive\b', re.I)),
    ('promotion:unresponsive', re.compile(r'\bunresponsive\b', re.I)),
    ('event:attendee', re.compile(r'\battendee\b', re.I)),
    ('event:absent', re.compile(r'\babsent\b', re.I)),
    ('social:active', re.compile(r'\bactive\b', re.I)),
    ('social:inactive', re.compile(r'\binactive\b', re.I)),
    ('support:active', re.compile(r'\bactive\b', re.I)),
    ('support:inactive', re.compile(r'\binactive\b', re.I)),
    ('feedback:positive', re.compile(r'\bpositive\b', re.I)),
    ('feedback:negative', re.compile(r'\bnegative\b', re.I)),
    ('stage:lead', re.compile(r'\blead\b', re.I)),
    ('stage:mql (marketing qualified)', re.compile(r'\bmql\ \(marketing\ qualified\)\b', re.I)),
    ('stage:sql (sales qualified)', re.compile(r'\bsql\ \(sales\ qualified\)\b', re.I)),
    ('stage:prospect', re.compile(r'\bprospect\b', re.I)),
    ('stage:customer', re.compile(r'\bcustomer\b', re.I)),
    ('stage:active', re.compile(r'\bactive\b', re.I)),
    ('stage:inactive', re.compile(r'\binactive\b', re.I)),
    ('stage:churn-risk', re.compile(r'\bchurn\-risk\b', re.I)),
    ('stage:churned', re.compile(r'\bchurned\b', re.I)),
    ('stage:advocate', re.compile(r'\badvocate\b', re.I)),
    ('stage:expansion', re.compile(r'\bexpansion\b', re.I)),
    ('stage:onboarding', re.compile(r'\bonboarding\b', re.I)),
    ('stage:nurturing', re.compile(r'\bnurturing\b', re.I)),
    ('stage:upsell', re.compile(r'\bupsell\b', re.I)),
    ('stage:renewal', re.compile(r'\brenewal\b', re.I)),
    ('stage:lost', re.compile(r'\blost\b', re.I)),
    ('stage:win', re.compile(r'\bwin\b', re.I)),
    ('stage:opportunity', re.compile(r'\bopportunity\b', re.I)),
    ('stage:trial', re.compile(r'\btrial\b', re.I)),
    ('stage:evaluation', re.compile(r'\bevaluation\b', re.I)),
    ('channel:email', re.compile(r'\bemail\b', re.I)),
    ('channel:sms', re.compile(r'\bsms\b', re.I)),
    ('channel:push', re.compile(r'\bpush\b', re.I)),
    ('channel:whatsapp', re.compile(r'\bwhatsapp\b', re.I)),
    ('channel:webChat', re.compile(r'\bwebchat\b', re.I)),
    ('channel: Instagram', re.compile(r'\binstagram\b', re.I)),
    ('channel: Facebook', re.compile(r'\bfacebook\b', re.I)),
    ('channel: Telegram', re.compile(r'\btelegram\b', re.I)),
    ('channel: BooForms', re.compile(r'\bbooforms\b', re.I)),
    ('channel: LandingPage', re.compile(r'\blandingpage\b', re.I)),
    ('channel: others', re.compile(r'\bothers\b', re.I)),
    ('device:mobile', re.compile(r'\bmobile\b', re.I)),
    ('device:desktop', re.compile(r'\bdesktop\b', re.I)),
    ('os:ios', re.compile(r'\bios\b', re.I)),
    ('os:android', re.compile(r'\bandroid\b', re.I)),
    ('traffic:direct', re.compile(r'\bdirect\b', re.I)),
    ('traffic:organic', re.compile(r'\borganic\b', re.I)),
    ('traffic:paid', re.compile(r'\bpaid\b', re.I)),
    ('traffic:referral', re.compile(r'\breferral\b', re.I)),
    ('source:campaign', re.compile(r'\bcampaign\b', re.I)),
    ('source:ads', re.compile(r'\bads\b', re.I)),
    ('source: outbound', re.compile(r'\boutbound\b', re.I)),
    ('source: influencer', re.compile(r'\binfluencer\b', re.I)),
    ('source:newsletter', re.compile(r'\bnewsletter\b', re.I)),
    ('recency:7d', re.compile(r'\b7d\b', re.I)),
    ('recency:30d', re.compile(r'\b30d\b', re.I)),
    ('recency:90d', re.compile(r'\b90d\b', re.I)),
    ('recency:180d', re.compile(r'\b180d\b', re.I)),
    ('frequency:1-5', re.compile(r'\b1\-5\b', re.I)),
    ('frequency:5-10', re.compile(r'\b5\-10\b', re.I)),
    ('frequency:10+', re.compile(r'\b10\+\b', re.I)),
    ('monetary:low', re.compile(r'\blow\b', re.I)),
    ('monetary:medium', re.compile(r'\bmedium\b', re.I)),
    ('monetary:high', re.compile(r'\bhigh\b', re.I)),
    ('rfm:vip', re.compile(r'\bvip\b', re.I)),
    ('rfm:at-risk', re.compile(r'\bat\-risk\b', re.I)),
    ('rfm:new', re.compile(r'\bnew\b', re.I)),
    ('rfm:champion', re.compile(r'\bchampion\b', re.I)),
    ('rfm:inactive', re.compile(r'\binactive\b', re.I)),
    ('cycle:short', re.compile(r'\bshort\b', re.I)),
    ('cycle:medium', re.compile(r'\bmedium\b', re.I)),
    ('cycle:long', re.compile(r'\blong\b', re.I)),
    ('value:high', re.compile(r'\bhigh\b', re.I)),
    ('value:low', re.compile(r'\blow\b', re.I)),
    ('value:Medium', re.compile(r'\bmedium\b', re.I)),
    ('purchase:one-time', re.compile(r'\bone\-time\b', re.I)),
    ('purchase:repeat', re.compile(r'\brepeat\b', re.I)),
    ('purchase:reccurent', re.compile(r'\breccurent\b', re.I)),
    ('cart: fill', re.compile(r'\bfill\b', re.I)),
    ('cart:abandoned', re.compile(r'\babandoned\b', re.I)),
    ('cart:completed', re.compile(r'\bcompleted\b', re.I)),
    ('price-sensitivity:high', re.compile(r'\bhigh\b', re.I)),
    ('price-sensitivity:low', re.compile(r'\blow\b', re.I)),
    ('product:core', re.compile(r'\bcore\b', re.I)),
    ('product:addons', re.compile(r'\baddons\b', re.I)),
    ('discount:user', re.compile(r'\buser\b', re.I)),
    ('discount:non-user', re.compile(r'\bnon\-user\b', re.I)),
    ('refund:yes', re.compile(r'\byes\b', re.I)),
    ('refund:no', re.compile(r'\bno\b', re.I)),
    ('returning:yes', re.compile(r'\byes\b', re.I)),
    ('returning:no', re.compile(r'\bno\b', re.I)),
    ('purchase:seasonal', re.compile(r'\bseasonal\b', re.I)),
    ('purchase:impulse', re.compile(r'\bimpulse\b', re.I)),
    ('purchase:planned', re.compile(r'\bplanned\b', re.I)),
    ('basket:high', re.compile(r'\bhigh\b', re.I)),
    ('basket:low', re.compile(r'\blow\b', re.I)),
    ('purchase:subscription', re.compile(r'\bsubscription\b', re.I)),
    ('tier:bronze', re.compile(r'\bbronze\b', re.I)),
    ('tier:silver', re.compile(r'\bsilver\b', re.I)),
    ('tier:gold', re.compile(r'\bgold\b', re.I)),
    ('tier:platinum', re.compile(r'\bplatinum\b', re.I)),
    ('profitability:low', re.compile(r'\blow\b', re.I)),
    ('profitability:high', re.compile(r'\bhigh\b', re.I)),
    ('margin:positive', re.compile(r'\bpositive\b', re.I)),
    ('margin:negative', re.compile(r'\bnegative\b', re.I)),
    ('customer-lifetime:short', re.compile(r'\bshort\b', re.I)),
    ('customer-lifetime:long', re.compile(r'\blong\b', re.I)),
    ('renewal-likelihood:high', re.compile(r'\bhigh\b', re.I)),
    ('renewal-likelihood:low', re.compile(r'\blow\b', re.I)),
    ('growth:high', re.compile(r'\bhigh\b', re.I)),
    ('growth:low', re.compile(r'\blow\b', re.I)),
    ('tier:enterprise', re.compile(r'\benterprise\b', re.I)),
    ('tier:startup', re.compile(r'\bstartup\b', re.I)),
    ('value:premium', re.compile(r'\bpremium\b', re.I)),
    ('value:standard', re.compile(r'\bstandard\b', re.I)),
    ('loyalty:long-term', re.compile(r'\blong\-term\b', re.I)),
    ('loyalty:new', re.compile(r'\bnew\b', re.I)),
    ('intent:buy', re.compile(r'\bbuy\b', re.I)),
    ('intent:research', re.compile(r'\bresearch\b', re.I)),
    ('intent:compare', re.compile(r'\bcompare\b', re.I)),
    ('urgency:high', re.compile(r'\bhigh\b', re.I)),
    ('urgency:medium', re.compile(r'\bmedium\b', re.I)),
    ('urgency:low', re.compile(r'\blow\b', re.I)),
    ('readiness:now', re.compile(r'\bnow\b', re.I)),
    ('readiness:later', re.compile(r'\blater\b', re.I)),
    ('interest:productA', re.compile(r'\bproducta\b', re.I)),
    ('interest:productB', re.compile(r'\bproductb\b', re.I)),
    ('intent:demo', re.compile(r'\bdemo\b', re.I)),
    ('intent:trial', re.compile(r'\btrial\b', re.I)),
    ('intent:upgrade', re.compile(r'\bupgrade\b', re.I)),
    ('intent:renew', re.compile(r'\brenew\b', re.I)),
    ('intent:contact', re.compile(r'\bcontact\b', re.I)),
    ('intent:pricing', re.compile(r'\bpricing\b', re.I)),
    ('intent:integration', re.compile(r'\bintegration\b', re.I)),
    ('pain:manual-process', re.compile(r'\bmanual\-process\b', re.I)),
    ('pain:slow-ops', re.compile(r'\bslow\-ops\b', re.I)),
    ('pain:data-silos', re.compile(r'\bdata\-silos\b', re.I)),
    ('pain:pipeline', re.compile(r'\bpipeline\b', re.I)),
    ('need:automation', re.compile(r'\bautomation\b', re.I)),
    ('need:ai', re.compile(r'\bai\b', re.I)),
    ('need:integration', re.compile(r'\bintegration\b', re.I)),
    ('need:insights', re.compile(r'\binsights\b', re.I)),
    ('need:training', re.compile(r'\btraining\b', re.I)),
    ('need:governance', re.compile(r'\bgovernance\b', re.I)),
    ('priority:high', re.compile(r'\bhigh\b', re.I)),
    ('priority:medium', re.compile(r'\bmedium\b', re.I)),
    ('priority:low', re.compile(r'\blow\b', re.I)),
    ('pain:complexity', re.compile(r'\bcomplexity\b', re.I)),
    ('pain:errors', re.compile(r'\berrors\b', re.I)),
    ('pain:overcost', re.compile(r'\bovercost\b', re.I)),
    ('need:migration', re.compile(r'\bmigration\b', re.I)),
    ('need:security', re.compile(r'\bsecurity\b', re.I)),
    ('need:performance', re.compile(r'\bperformance\b', re.I)),
    ('need:scalability', re.compile(r'\bscalability\b', re.I)),
    ('predict:churn-high', re.compile(r'\bchurn\-high\b', re.I)),
    ('predict:churn-medium', re.compile(r'\bchurn\-medium\b', re.I)),
    ('predict:churn-low', re.compile(r'\bchurn\-low\b', re.I)),
    ('predict:upsell-high', re.compile(r'\bupsell\-high\b', re.I)),
    ('predict:upsell-low', re.compile(r'\bupsell\-low\b', re.I)),
    ('predict:conversion-high', re.compile(r'\bconversion\-high\b', re.I)),
    ('predict:conversion-low', re.compile(r'\bconversion\-low\b', re.I)),
    ('score:loyalty', re.compile(r'\bloyalty\b', re.I)),
    ('score:engagement', re.compile(r'\bengagement\b', re.I)),
    ('score:health', re.compile(r'\bhealth\b', re.I)),
    ('risk:high', re.compile(r'\bhigh\b', re.I)),
    ('risk:medium', re.compile(r'\bmedium\b', re.I)),
    ('risk:low', re.compile(r'\blow\b', re.I)),
    ('opportunity:high', re.compile(r'\bhigh\b', re.I)),
    ('opportunity:medium', re.compile(r'\bmedium\b', re.I)),
    ('opportunity:low', re.compile(r'\blow\b', re.I)),
    ('forecast:positive', re.compile(r'\bpositive\b', re.I)),
    ('forecast:negative', re.compile(r'\bnegative\b', re.I)),
    ('propensity:buy', re.compile(r'\bbuy\b', re.I)),
    ('propensity:upgrade', re.compile(r'\bupgrade\b', re.I)),
]