TAG_SIGNALS_GEN = [
    ('age: - 18', re.compile(r'.*.*18', re.I)),
    ('age:18-24', re.compile(r'18.*24', re.I)),
    ('age:25-34', re.compile(r'25.*34', re.I)),
    ('age:35-44', re.compile(r'35.*44', re.I)),
    ('age:45-54', re.compile(r'45.*54', re.I)),
    ('age:55-64', re.compile(r'55.*64', re.I)),
    ('age: + 65', re.compile(r'.*.*65', re.I)),
    ('gender:male', re.compile(r'male', re.I)),
    ('gender:female', re.compile(r'female', re.I)),
    ('gender:Other', re.compile(r'other', re.I)),
    ('education:highschool', re.compile(r'highschool', re.I)),
    ('education:bachelor', re.compile(r'bachelor', re.I)),
    ('education:master', re.compile(r'master', re.I)),
    ('education:phd', re.compile(r'phd', re.I)),
    ('education:college', re.compile(r'college', re.I)),
    ('country:fr', re.compile(r'fr', re.I)),
    ('country:ma', re.compile(r'ma', re.I)),
    ('country:es', re.compile(r'es', re.I)),
    ('country:us', re.compile(r'us', re.I)),
    ('city:casablanca', re.compile(r'casablanca', re.I)),
    ('city:rabat', re.compile(r'rabat', re.I)),
    ('city:paris', re.compile(r'paris', re.I)),
    ('city: 100 Pays 200 Villes', re.compile(r'100.*pays.*200.*villes', re.I)),
    ('language:fr', re.compile(r'fr', re.I)),
    ('language:ar', re.compile(r'ar', re.I)),
    ('language:en', re.compile(r'en', re.I)),
    ('language:esp', re.compile(r'esp', re.I)),
    ('personality:analytical', re.compile(r'analytical', re.I)),
    ('personality:creative', re.compile(r'creative', re.I)),
    ('personality: Social', re.compile(r'social', re.I)),
    ('personality: Procedural', re.compile(r'procedural', re.I)),
    ('preference:premium', re.compile(r'premium', re.I)),
    ('preference:lowcost', re.compile(r'lowcost', re.I)),
    ('preference: Innovative', re.compile(r'innovative', re.I)),
    ('preference: quality', re.compile(r'quality', re.I)),
    ('interest: IT&AI&Automation', re.compile(r'it.*ai.*automation', re.I)),
    ('interest: Technology&innovation', re.compile(r'technology.*innovation', re.I)),
    ('interest:properties', re.compile(r'properties', re.I)),
    ('interest: physics & biology', re.compile(r'physics.*.*.*biology', re.I)),
    ('interest: Art&design', re.compile(r'art.*design', re.I)),
    ('interest: cars&plane', re.compile(r'cars.*plane', re.I)),
    ('motivation:performance', re.compile(r'performance', re.I)),
    ('motivation:simplicity', re.compile(r'simplicity', re.I)),
    ('attitude:early-adopter', re.compile(r'early.*adopter', re.I)),
    ('attitude:late-adopter', re.compile(r'late.*adopter', re.I)),
    ('expectation:quality', re.compile(r'quality', re.I)),
    ('expectation:speed', re.compile(r'speed', re.I)),
    ('style:premium', re.compile(r'premium', re.I)),
    ('style:basic', re.compile(r'basic', re.I)),
    ('role: guest', re.compile(r'guest', re.I)),
    ('role: authenticated', re.compile(r'authenticated', re.I)),
    ('role: indentified', re.compile(r'indentified', re.I)),
    ('role : possibly identfied', re.compile(r'possibly.*identfied', re.I)),
    ('access: role based', re.compile(r'role.*based', re.I)),
    ('access:guest based', re.compile(r'guest.*based', re.I)),
    ('company-size:1-10', re.compile(r'1.*10', re.I)),
    ('company-size:10-50', re.compile(r'10.*50', re.I)),
    ('company-size:50-200', re.compile(r'50.*200', re.I)),
    ('company-size:200-1000', re.compile(r'200.*1000', re.I)),
    ('company-size:1000+', re.compile(r'1000.*', re.I)),
    ('revenue:1m', re.compile(r'1m', re.I)),
    ('revenue:5m', re.compile(r'5m', re.I)),
    ('revenue:20m+', re.compile(r'20m.*', re.I)),
    ('market:local', re.compile(r'local', re.I)),
    ('market:regional', re.compile(r'regional', re.I)),
    ('market:global', re.compile(r'global', re.I)),
    ('growth:fast', re.compile(r'fast', re.I)),
    ('growth:stable', re.compile(r'stable', re.I)),
    ('ownership:private', re.compile(r'private', re.I)),
    ('ownership:public', re.compile(r'public', re.I)),
    ('model:b2b', re.compile(r'b2b', re.I)),
    ('model: b2g', re.compile(r'b2g', re.I)),
    ('model:b2c', re.compile(r'b2c', re.I)),
    ('model:service', re.compile(r'service', re.I)),
    ('model: integration', re.compile(r'integration', re.I)),
    ('model: distribution', re.compile(r'distribution', re.I)),
    ('industry:finance', re.compile(r'finance', re.I)),
    ('industry:health', re.compile(r'health', re.I)),
    ('industry:retail', re.compile(r'retail', re.I)),
    ('industry:manufacturing', re.compile(r'manufacturing', re.I)),
    ('industry:telco', re.compile(r'telco', re.I)),
    ('industry: Service', re.compile(r'service', re.I)),
    ('industry:primary sectors', re.compile(r'primary.*sectors', re.I)),
    ('industry:insurance', re.compile(r'insurance', re.I)),
    ('industry:education', re.compile(r'education', re.I)),
    ('industry:transport', re.compile(r'transport', re.I)),
    ('industry:energy', re.compile(r'energy', re.I)),
    ('industry:agriculture', re.compile(r'agriculture', re.I)),
    ('regulation:gdpr', re.compile(r'gdpr', re.I)),
    ('regulation:hipaa', re.compile(r'hipaa', re.I)),
    ('sector:public', re.compile(r'public', re.I)),
    ('sector:private', re.compile(r'private', re.I)),
    ('role:cto', re.compile(r'cto', re.I)),
    ('role:ceo', re.compile(r'ceo', re.I)),
    ('role:cfo', re.compile(r'cfo', re.I)),
    ('role:cmo', re.compile(r'cmo', re.I)),
    ('role:product-manager', re.compile(r'product.*manager', re.I)),
    ('role:developer', re.compile(r'developer', re.I)),
    ('role:data-analyst', re.compile(r'data.*analyst', re.I)),
    ('role:designer', re.compile(r'designer', re.I)),
    ('role:consultant', re.compile(r'consultant', re.I)),
    ('role:engineer', re.compile(r'engineer', re.I)),
    ('role:administrator', re.compile(r'administrator', re.I)),
    ('seniority:executive', re.compile(r'executive', re.I)),
    ('seniority:director', re.compile(r'director', re.I)),
    ('seniority:manager', re.compile(r'manager', re.I)),
    ('seniority:staff', re.compile(r'staff', re.I)),
    ('department:it', re.compile(r'it', re.I)),
    ('department:finance', re.compile(r'finance', re.I)),
    ('department:marketing', re.compile(r'marketing', re.I)),
    ('buyer:buyer', re.compile(r'buyer', re.I)),
    ('buyer:no', re.compile(r'no', re.I)),
    ('buyer: influencer', re.compile(r'influencer', re.I)),
    ('buyer: recommender', re.compile(r'recommender', re.I)),
    ('buyer: initiator', re.compile(r'initiator', re.I)),
    ('buyer: decider', re.compile(r'decider', re.I)),
    ('buyer role: End user', re.compile(r'end.*user', re.I)),
    ('budget:low', re.compile(r'low', re.I)),
    ('budget:medium', re.compile(r'medium', re.I)),
    ('budget:high', re.compile(r'high', re.I)),
    ('budget:none', re.compile(r'none', re.I)),
    ('authority:high', re.compile(r'high', re.I)),
    ('authority:medium', re.compile(r'medium', re.I)),
    ('authority:low', re.compile(r'low', re.I)),
    ('authority:none', re.compile(r'none', re.I)),
    ('need:urgent', re.compile(r'urgent', re.I)),
    ('need:medium', re.compile(r'medium', re.I)),
    ('need:low', re.compile(r'low', re.I)),
    ('need:none', re.compile(r'none', re.I)),
    ('timing:now', re.compile(r'now', re.I)),
    ('timing:3months', re.compile(r'3months', re.I)),
    ('timing:6months', re.compile(r'6months', re.I)),
    ('timing : none', re.compile(r'none', re.I)),
    ('fit:strong', re.compile(r'strong', re.I)),
    ('fit:weak', re.compile(r'weak', re.I)),
    ('fit:medium', re.compile(r'medium', re.I)),
    ('fit: none', re.compile(r'none', re.I)),
    ('sessions:daily', re.compile(r'daily', re.I)),
    ('sessions:weekly', re.compile(r'weekly', re.I)),
    ('sessions:monthly', re.compile(r'monthly', re.I)),
    ('usage:low', re.compile(r'low', re.I)),
    ('usage:medium', re.compile(r'medium', re.I)),
    ('usage:high', re.compile(r'high', re.I)),
    ('active:7days', re.compile(r'7days', re.I)),
    ('active:30days', re.compile(r'30days', re.I)),
    ('events:10+', re.compile(r'10.*', re.I)),
    ('events:100+', re.compile(r'100.*', re.I)),
    ('engagement:power-user', re.compile(r'power.*user', re.I)),
    ('engagement:occasional', re.compile(r'occasional', re.I)),
    ('login:frequent', re.compile(r'frequent', re.I)),
    ('login:rare', re.compile(r'rare', re.I)),
    ('consumption:high', re.compile(r'high', re.I)),
    ('consumption:low', re.compile(r'low', re.I)),
    ('stickiness:high', re.compile(r'high', re.I)),
    ('stickiness:low', re.compile(r'low', re.I)),
    ('depth:shallow', re.compile(r'shallow', re.I)),
    ('depth:deep', re.compile(r'deep', re.I)),
    ('feature-depth:basic', re.compile(r'basic', re.I)),
    ('feature-depth:medium', re.compile(r'medium', re.I)),
    ('adoption:features 1', re.compile(r'features.*1', re.I)),
    ('adoption:features 2', re.compile(r'features.*2', re.I)),
    ('adoption:features 3', re.compile(r'features.*3', re.I)),
    ('adoption:features 4', re.compile(r'features.*4', re.I)),
    ('adoption:features 5', re.compile(r'features.*5', re.I)),
    ('adoption:features 6', re.compile(r'features.*6', re.I)),
    ('adoption:features 7', re.compile(r'features.*7', re.I)),
    ('email:opened', re.compile(r'opened', re.I)),
    ('email:clicked', re.compile(r'clicked', re.I)),
    ('email:ignored', re.compile(r'ignored', re.I)),
    ('push:enabled', re.compile(r'enabled', re.I)),
    ('push:disabled', re.compile(r'disabled', re.I)),
    ('web:active', re.compile(r'active', re.I)),
    ('web:inactive', re.compile(r'inactive', re.I)),
    ('loyalty:high', re.compile(r'high', re.I)),
    ('loyalty:medium', re.compile(r'medium', re.I)),
    ('loyalty:low', re.compile(r'low', re.I)),
    ('promotion:responsive', re.compile(r'responsive', re.I)),
    ('promotion:unresponsive', re.compile(r'unresponsive', re.I)),
    ('event:attendee', re.compile(r'attendee', re.I)),
    ('event:absent', re.compile(r'absent', re.I)),
    ('social:active', re.compile(r'active', re.I)),
    ('social:inactive', re.compile(r'inactive', re.I)),
    ('support:active', re.compile(r'active', re.I)),
    ('support:inactive', re.compile(r'inactive', re.I)),
    ('feedback:positive', re.compile(r'positive', re.I)),
    ('feedback:negative', re.compile(r'negative', re.I)),
    ('stage:lead', re.compile(r'lead', re.I)),
    ('stage:mql (marketing qualified)', re.compile(r'mql.*.*marketing.*qualified.*', re.I)),
    ('stage:sql (sales qualified)', re.compile(r'sql.*.*sales.*qualified.*', re.I)),
    ('stage:prospect', re.compile(r'prospect', re.I)),
    ('stage:customer', re.compile(r'customer', re.I)),
    ('stage:active', re.compile(r'active', re.I)),
    ('stage:inactive', re.compile(r'inactive', re.I)),
    ('stage:churn-risk', re.compile(r'churn.*risk', re.I)),
    ('stage:churned', re.compile(r'churned', re.I)),
    ('stage:advocate', re.compile(r'advocate', re.I)),
    ('stage:expansion', re.compile(r'expansion', re.I)),
    ('stage:onboarding', re.compile(r'onboarding', re.I)),
    ('stage:nurturing', re.compile(r'nurturing', re.I)),
    ('stage:upsell', re.compile(r'upsell', re.I)),
    ('stage:renewal', re.compile(r'renewal', re.I)),
    ('stage:lost', re.compile(r'lost', re.I)),
    ('stage:win', re.compile(r'win', re.I)),
    ('stage:opportunity', re.compile(r'opportunity', re.I)),
    ('stage:trial', re.compile(r'trial', re.I)),
    ('stage:evaluation', re.compile(r'evaluation', re.I)),
    ('channel:email', re.compile(r'email', re.I)),
    ('channel:sms', re.compile(r'sms', re.I)),
    ('channel:push', re.compile(r'push', re.I)),
    ('channel:whatsapp', re.compile(r'whatsapp', re.I)),
    ('channel:webChat', re.compile(r'webchat', re.I)),
    ('channel: Instagram', re.compile(r'instagram', re.I)),
    ('channel: Facebook', re.compile(r'facebook', re.I)),
    ('channel: Telegram', re.compile(r'telegram', re.I)),
    ('channel: BooForms', re.compile(r'booforms', re.I)),
    ('channel: LandingPage', re.compile(r'landingpage', re.I)),
    ('channel: others', re.compile(r'others', re.I)),
    ('device:mobile', re.compile(r'mobile', re.I)),
    ('device:desktop', re.compile(r'desktop', re.I)),
    ('os:ios', re.compile(r'ios', re.I)),
    ('os:android', re.compile(r'android', re.I)),
    ('traffic:direct', re.compile(r'direct', re.I)),
    ('traffic:organic', re.compile(r'organic', re.I)),
    ('traffic:paid', re.compile(r'paid', re.I)),
    ('traffic:referral', re.compile(r'referral', re.I)),
    ('source:campaign', re.compile(r'campaign', re.I)),
    ('source:ads', re.compile(r'ads', re.I)),
    ('source: outbound', re.compile(r'outbound', re.I)),
    ('source: influencer', re.compile(r'influencer', re.I)),
    ('source:newsletter', re.compile(r'newsletter', re.I)),
    ('recency:7d', re.compile(r'7d', re.I)),
    ('recency:30d', re.compile(r'30d', re.I)),
    ('recency:90d', re.compile(r'90d', re.I)),
    ('recency:180d', re.compile(r'180d', re.I)),
    ('frequency:1-5', re.compile(r'1.*5', re.I)),
    ('frequency:5-10', re.compile(r'5.*10', re.I)),
    ('frequency:10+', re.compile(r'10.*', re.I)),
    ('monetary:low', re.compile(r'low', re.I)),
    ('monetary:medium', re.compile(r'medium', re.I)),
    ('monetary:high', re.compile(r'high', re.I)),
    ('rfm:vip', re.compile(r'vip', re.I)),
    ('rfm:at-risk', re.compile(r'at.*risk', re.I)),
    ('rfm:new', re.compile(r'new', re.I)),
    ('rfm:champion', re.compile(r'champion', re.I)),
    ('rfm:inactive', re.compile(r'inactive', re.I)),
    ('cycle:short', re.compile(r'short', re.I)),
    ('cycle:medium', re.compile(r'medium', re.I)),
    ('cycle:long', re.compile(r'long', re.I)),
    ('value:high', re.compile(r'high', re.I)),
    ('value:low', re.compile(r'low', re.I)),
    ('value:Medium', re.compile(r'medium', re.I)),
    ('purchase:one-time', re.compile(r'one.*time', re.I)),
    ('purchase:repeat', re.compile(r'repeat', re.I)),
    ('purchase:reccurent', re.compile(r'reccurent', re.I)),
    ('cart: fill', re.compile(r'fill', re.I)),
    ('cart:abandoned', re.compile(r'abandoned', re.I)),
    ('cart:completed', re.compile(r'completed', re.I)),
    ('price-sensitivity:high', re.compile(r'high', re.I)),
    ('price-sensitivity:low', re.compile(r'low', re.I)),
    ('product:core', re.compile(r'core', re.I)),
    ('product:addons', re.compile(r'addons', re.I)),
    ('discount:user', re.compile(r'user', re.I)),
    ('discount:non-user', re.compile(r'non.*user', re.I)),
    ('refund:yes', re.compile(r'yes', re.I)),
    ('refund:no', re.compile(r'no', re.I)),
    ('returning:yes', re.compile(r'yes', re.I)),
    ('returning:no', re.compile(r'no', re.I)),
    ('purchase:seasonal', re.compile(r'seasonal', re.I)),
    ('purchase:impulse', re.compile(r'impulse', re.I)),
    ('purchase:planned', re.compile(r'planned', re.I)),
    ('basket:high', re.compile(r'high', re.I)),
    ('basket:low', re.compile(r'low', re.I)),
    ('purchase:subscription', re.compile(r'subscription', re.I)),
    ('tier:bronze', re.compile(r'bronze', re.I)),
    ('tier:silver', re.compile(r'silver', re.I)),
    ('tier:gold', re.compile(r'gold', re.I)),
    ('tier:platinum', re.compile(r'platinum', re.I)),
    ('profitability:low', re.compile(r'low', re.I)),
    ('profitability:high', re.compile(r'high', re.I)),
    ('margin:positive', re.compile(r'positive', re.I)),
    ('margin:negative', re.compile(r'negative', re.I)),
    ('customer-lifetime:short', re.compile(r'short', re.I)),
    ('customer-lifetime:long', re.compile(r'long', re.I)),
    ('renewal-likelihood:high', re.compile(r'high', re.I)),
    ('renewal-likelihood:low', re.compile(r'low', re.I)),
    ('growth:high', re.compile(r'high', re.I)),
    ('growth:low', re.compile(r'low', re.I)),
    ('tier:enterprise', re.compile(r'enterprise', re.I)),
    ('tier:startup', re.compile(r'startup', re.I)),
    ('value:premium', re.compile(r'premium', re.I)),
    ('value:standard', re.compile(r'standard', re.I)),
    ('loyalty:long-term', re.compile(r'long.*term', re.I)),
    ('loyalty:new', re.compile(r'new', re.I)),
    ('intent:buy', re.compile(r'buy', re.I)),
    ('intent:research', re.compile(r'research', re.I)),
    ('intent:compare', re.compile(r'compare', re.I)),
    ('urgency:high', re.compile(r'high', re.I)),
    ('urgency:medium', re.compile(r'medium', re.I)),
    ('urgency:low', re.compile(r'low', re.I)),
    ('readiness:now', re.compile(r'now', re.I)),
    ('readiness:later', re.compile(r'later', re.I)),
    ('interest:productA', re.compile(r'producta', re.I)),
    ('interest:productB', re.compile(r'productb', re.I)),
    ('intent:demo', re.compile(r'demo', re.I)),
    ('intent:trial', re.compile(r'trial', re.I)),
    ('intent:upgrade', re.compile(r'upgrade', re.I)),
    ('intent:renew', re.compile(r'renew', re.I)),
    ('intent:contact', re.compile(r'contact', re.I)),
    ('intent:pricing', re.compile(r'pricing', re.I)),
    ('intent:integration', re.compile(r'integration', re.I)),
    ('pain:manual-process', re.compile(r'manual.*process', re.I)),
    ('pain:slow-ops', re.compile(r'slow.*ops', re.I)),
    ('pain:data-silos', re.compile(r'data.*silos', re.I)),
    ('pain:pipeline', re.compile(r'pipeline', re.I)),
    ('need:automation', re.compile(r'automation', re.I)),
    ('need:ai', re.compile(r'ai', re.I)),
    ('need:integration', re.compile(r'integration', re.I)),
    ('need:insights', re.compile(r'insights', re.I)),
    ('need:training', re.compile(r'training', re.I)),
    ('need:governance', re.compile(r'governance', re.I)),
    ('priority:high', re.compile(r'high', re.I)),
    ('priority:medium', re.compile(r'medium', re.I)),
    ('priority:low', re.compile(r'low', re.I)),
    ('pain:complexity', re.compile(r'complexity', re.I)),
    ('pain:errors', re.compile(r'errors', re.I)),
    ('pain:overcost', re.compile(r'overcost', re.I)),
    ('need:migration', re.compile(r'migration', re.I)),
    ('need:security', re.compile(r'security', re.I)),
    ('need:performance', re.compile(r'performance', re.I)),
    ('need:scalability', re.compile(r'scalability', re.I)),
    ('predict:churn-high', re.compile(r'churn.*high', re.I)),
    ('predict:churn-medium', re.compile(r'churn.*medium', re.I)),
    ('predict:churn-low', re.compile(r'churn.*low', re.I)),
    ('predict:upsell-high', re.compile(r'upsell.*high', re.I)),
    ('predict:upsell-low', re.compile(r'upsell.*low', re.I)),
    ('predict:conversion-high', re.compile(r'conversion.*high', re.I)),
    ('predict:conversion-low', re.compile(r'conversion.*low', re.I)),
    ('score:loyalty', re.compile(r'loyalty', re.I)),
    ('score:engagement', re.compile(r'engagement', re.I)),
    ('score:health', re.compile(r'health', re.I)),
    ('risk:high', re.compile(r'high', re.I)),
    ('risk:medium', re.compile(r'medium', re.I)),
    ('risk:low', re.compile(r'low', re.I)),
    ('opportunity:high', re.compile(r'high', re.I)),
    ('opportunity:medium', re.compile(r'medium', re.I)),
    ('opportunity:low', re.compile(r'low', re.I)),
    ('forecast:positive', re.compile(r'positive', re.I)),
    ('forecast:negative', re.compile(r'negative', re.I)),
    ('propensity:buy', re.compile(r'buy', re.I)),
    ('propensity:upgrade', re.compile(r'upgrade', re.I)),
]